# Generated by Django 4.0.1 on 2022-01-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api.category')),
            ],
            options={
                'verbose_name_plural': 'segment categories',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(help_text='audio segment color label', max_length=20, verbose_name='audio segment color')),
                ('ini', models.FloatField(help_text='audio segment ini label', verbose_name='audio segment ini')),
                ('end', models.FloatField(help_text='audio segment end label', verbose_name='audio segment end')),
                ('comment', models.TextField()),
                ('categories', models.ForeignKey(help_text='select categories', on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'audio segment',
                'verbose_name_plural': 'audio segments',
                'db_table': 'audio_segment',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='audio file label', max_length=150, verbose_name='audio name')),
                ('file_type', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(help_text='select segment', on_delete=django.db.models.deletion.CASCADE, to='api.segment', verbose_name='segment')),
            ],
            options={
                'verbose_name': 'audio file',
                'verbose_name_plural': 'audio files',
                'db_table': 'audio_file',
            },
        ),
    ]
