# Generated by Django 4.0.1 on 2022-01-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='buffer',
            field=models.CharField(default=0, help_text='audio buffer label', max_length=255, verbose_name='audio buffer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file_type',
            field=models.CharField(help_text='audio type label', max_length=10, verbose_name='audio type'),
        ),
    ]
