# Generated by Django 4.0.1 on 2022-01-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_audiofile_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='comment',
            field=models.TextField(blank=True, help_text='segment comment label', verbose_name='segment comment'),
        ),
    ]
