# Generated by Django 4.0.1 on 2022-01-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_segment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='segment',
        ),
        migrations.AddField(
            model_name='segment',
            name='audio',
            field=models.ForeignKey(default=0, help_text='select audio clip', on_delete=django.db.models.deletion.CASCADE, to='api.audiofile', verbose_name='audio clip'),
            preserve_default=False,
        ),
    ]
