# Generated by Django 4.0.1 on 2022-01-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_audiofile_segment_segment_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='categories',
        ),
        migrations.AddField(
            model_name='segment',
            name='category',
            field=models.ForeignKey(default=0, help_text='select category', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.category', verbose_name='category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='sub_category',
            field=models.ForeignKey(default=0, help_text='select subcategory', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.category', verbose_name='subcategory'),
            preserve_default=False,
        ),
    ]
