# Generated by Django 4.0.1 on 2022-01-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_segment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='color',
            field=models.CharField(help_text='audio segment color label', max_length=50, verbose_name='audio segment color'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='comment',
            field=models.TextField(blank=True, help_text='segment comment label', verbose_name='segment comment'),
        ),
    ]
