# Generated by Django 4.0.1 on 2022-02-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_segment_color_alter_segment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='buffer',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.IntegerField(default=0, help_text='audio duration label', verbose_name='audio duration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiofile',
            name='length',
            field=models.IntegerField(default=0, help_text='audio length label', verbose_name='audio length'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiofile',
            name='numberOfChannels',
            field=models.IntegerField(default=0, help_text='audio numberOfChannels label', verbose_name='audio numberOfChannels'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiofile',
            name='sampleRate',
            field=models.IntegerField(default=0, help_text='audio sampleRate label', verbose_name='audio sampleRate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='segment',
            name='width',
            field=models.FloatField(default=0, help_text='audio segment width label', verbose_name='audio segment width'),
            preserve_default=False,
        ),
    ]
