# Generated by Django 4.0.1 on 2022-02-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_audiofile_buffer_audiofile_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='duration',
            field=models.FloatField(help_text='audio duration label', verbose_name='audio duration'),
        ),
    ]
